 const clubdet=[
    {
       name:"Cricket",
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpa0QBQ9-sYDLtn2f6__6372F7DJCf_2-HJw&usqp=CAU",
       followers:"0",
       members:"0"   
    },
    {
      name:"Football",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Tennis",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Volleyball",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Basketball",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Badminton",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Table Tennis",
      img:"" ,
      followers:"0",
      members:"0"  
   },
   {
      name:"Chess",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Saaj",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Avartan",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Samvaad",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Jazbaat",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Jagrati",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"",
      img:"",
      followers:"0",
      members:"0"   
   },
 ]
//  function CLUBDET(){
//     return clubdet;
// }
export default clubdet;