const commdet=[
    {
       name:"CP",
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpa0QBQ9-sYDLtn2f6__6372F7DJCf_2-HJw&usqp=CAU",
       followers:"0",
       members:"0"   
    },
    {
      name:"Web Dev",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"AI/ML",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Design",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Core-Mechanical",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Core-Electronics",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Core-SM",
      img:"" ,
      followers:"0",
      members:"0"  
   },
   {
      name:"Core-CS",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"DSA",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Samvaad",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Jazbaat",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"Jagrati",
      img:"",
      followers:"0",
      members:"0"   
   },
   {
      name:"",
      img:"",
      followers:"0",
      members:"0"   
   },
 ]
//  function CLUBDET(){
//     return clubdet;
// }
export default commdet;